// fittrackee_client/src/components/Dashboard/CalendarWorkout.jsx
import React from 'react'
import { Link } from 'react-router-dom'

import { recordsLabels } from '../../utils/workouts'

export default function CalendarWorkout(props) {
  const { isDisabled, isMore, sportImg, workout } = props
  return (
    <Link
      className={`calendar-workout${isMore}`}
      to={`/workouts/${workout.id}`}
    >
      <>
        <img
          alt="workout sport logo"
          className={`workout-sport ${isDisabled}`}
          src={sportImg}
          title={workout.title}
        />
        {workout.records.length > 0 && (
          <sup>
            <i
              className="fa fa-trophy custom-fa-small"
              aria-hidden="true"
              title={workout.records.map(
                rec =>
                  ` ${
                    recordsLabels.filter(
                      r => r.record_type === rec.record_type
                    )[0].label
                  }`
              )}
            />
          </sup>
        )}
      </>
    </Link>
  )
}

// fittrackee_client/src/components/Dashboard/UserCalendar/CalendarWorkout.vue
<template>
  <div class="calendar-workout">
    <img alt="workout sport logo" :src="sportImg" :title="workout.title" />
    <sup>
      <i
        v-if="workout.records.length > 0"
        class="fa fa-trophy custom-fa-small"
        aria-hidden="true"
        :title="
          workout.records.map(
            (record) => ` ${t(`workouts.RECORD_${record.record_type}`)}`
          )
        "
      />
    </sup>
  </div>
</template>

<script lang="ts">
  import { defineComponent, PropType } from 'vue'
  import { useI18n } from 'vue-i18n'

  import { IWorkout } from '@/types/workouts'

  export default defineComponent({
    name: 'CalendarWorkouts',
    props: {
      workout: {
        type: Object as PropType<IWorkout>,
        required: true,
      },
      sportImg: {
        type: String,
        required: true,
      },
    },
    setup() {
      const { t } = useI18n()
      return { t }
    },
  })
</script>

<style lang="scss">
  @import '~@/scss/base';

  .calendar-workout {
    padding: 2px 0;
    img {
      max-width: 18px;
      max-height: 18px;
    }
    sup {
      position: relative;
      top: -0.6em;
      left: -0.4em;
      .custom-fa-small {
        font-size: 0.7em;
      }
    }

    @media screen and (max-width: $small-limit) {
      img {
        max-width: 14px;
        max-height: 14px;
      }
      sup {
        .custom-fa-small {
          font-size: 0.6em;
        }
      }
    }
  }
</style>
