// fittrackee_client/src/components/Dashboard/UserCalendar/CalendarWorkouts.vue
<template>
  <div class="calendar-workouts">
    <div v-for="(workout, index) in workouts" :key="index">
      <CalendarWorkout
        :workout="workout"
        :sportImg="getSportImg(workout, sports)"
      />
    </div>
  </div>
</template>

<script lang="ts">
  import { defineComponent, PropType } from 'vue'

  import CalendarWorkout from '@/components/Dashboard/UserCalendar/CalendarWorkout.vue'
  import { ISport } from '@/types/sports'
  import { IWorkout } from '@/types/workouts'

  export default defineComponent({
    name: 'CalendarWorkouts',
    components: {
      CalendarWorkout,
    },
    props: {
      workouts: {
        type: Object as PropType<IWorkout[]>,
        required: true,
      },
      sports: {
        type: Object as PropType<ISport[]>,
        required: true,
      },
    },
    setup() {
      function getSportImg(workout: IWorkout, sports: ISport[]): string {
        return sports
          .filter((sport) => sport.id === workout.sport_id)
          .map((sport) => sport.img)[0]
      }
      return { getSportImg }
    },
  })
</script>

<style lang="scss"></style>

// fittrackee_client_old/src/components/Dashboard/CalendarWorkouts.jsx
import React from 'react'

import CalendarWorkout from './CalendarWorkout'

export default class CalendarWorkouts extends React.Component {
  constructor(props, context) {
    super(props, context)
    this.state = {
      isHidden: true,
    }
  }

  handleDisplayMore() {
    this.setState({
      isHidden: !this.state.isHidden,
    })
  }

  render() {
    const { dayWorkouts, isDisabled, sports } = this.props
    const { isHidden } = this.state
    return (
      <div>
        {dayWorkouts.map(act => (
          <CalendarWorkout
            key={act.id}
            workout={act}
            isDisabled={isDisabled}
            isMore=""
            sportImg={sports.filter(s => s.id === act.sport_id).map(s => s.img)}
          />
        ))}
        {dayWorkouts.length > 2 && (
          <i
            className={`fa fa-${isHidden ? 'plus' : 'times'} calendar-more`}
            aria-hidden="true"
            onClick={() => this.handleDisplayMore()}
            title="show more workouts"
          />
        )}
        {!isHidden && (
          <div className="calendar-display-more">
            {dayWorkouts.map(act => (
              <CalendarWorkout
                key={act.id}
                workout={act}
                isDisabled={isDisabled}
                isMore="-more"
                sportImg={sports
                  .filter(s => s.id === act.sport_id)
                  .map(s => s.img)}
              />
            ))}
          </div>
        )}
      </div>
    )
  }
}
