// fittrackee_client/src/views/NotFound.vue
<template>
  <div class="not-found">
    <Error
      title="404"
      :message="t('error.not-found.PAGE')"
      :button-text="t('common.HOME')"
    />
  </div>
</template>

<script lang="ts">
  import { defineComponent } from 'vue'
  import { useI18n } from 'vue-i18n'
  import Error from '@/components/Error.vue'

  export default defineComponent({
    name: 'NotFound',
    components: {
      Error,
    },
    setup() {
      const { t } = useI18n()
      return { t }
    },
  })
</script>

// fittrackee_client/src/components/Others/NotFound.jsx
import React from 'react'
import { Helmet } from 'react-helmet'
import { useTranslation } from 'react-i18next'

export default function NotFound() {
  const { t } = useTranslation()
  return (
    <div>
      <Helmet>
        <title>fittrackee - 404</title>
      </Helmet>
      <h1 className="page-title">{t('Page not found')}</h1>
    </div>
  )
}
